name: UrlShortener

options:
  defaultConfig: Release
  deploymentTarget:
    iOS: 15.0

configs:
  Debug: debug
  Release: release

settings:
  base:
    # Project
    SWIFT_VERSION: 5
    SDKROOT: iphoneos
    ENABLE_USER_SCRIPT_SANDBOXING: 'NO'
    SWIFT_EMIT_LOC_STRINGS: 'NO'
    LOCALIZED_STRING_SWIFTUI_SUPPORT: 'NO'
    PRODUCT_BUNDLE_IDENTIFIER: com.edyuto.$(PRODUCT_NAME)
    PRODUCT_NAME: $(TARGET_NAME)
    STRIP_INSTALLED_PRODUCT: 'NO'
    ALWAYS_SEARCH_USER_PATHS: 'NO'

    # Target
    IPHONEOS_DEPLOYMENT_TARGET: '15.0'
    TARGET_DEVICE_FAMILY: '1'
    
    # Signing
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: iPhone Developer
    DEVELOPMENT_TEAM: 2X5PWXY74F
    PROVISIONING_PROFILE:
    PROVISIONING_PROFILE_SPECIFIER:
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG $(inherited)
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      ENABLE_TESTABILITY: 'YES'
      ONLY_ACTIVE_ARCH: 'YES'
    Release:
      SWIFT_COMPILATION_MODE: wholemodule

projectReferences:
  Cache:
    path: Modules/Cache/Cache.xcodeproj
  Logger:
    path: Modules/Logger/DebugLogger.xcodeproj
  Network:
    path: Modules/Network/Network.xcodeproj

targets:
  UrlShortener:
    type: application
    platform: iOS
    sources: [UrlShortener]
    dependencies:
      - target: Cache/CacheProvider
      - target: Logger/DebugLoggerProvider
      - target: Network/NetworkProvider
    postBuildScripts:
      - script: chmod +x ./Scripts/lint-checker
        name: Lint permissions
        basedOnDependencyAnalysis: false
      - script: ./Scripts/lint-checker
        name: SwiftLint
        basedOnDependencyAnalysis: false
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: 'AppIcon'
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
        INFOPLIST_FILE: UrlShortener/Resources/Info.plist
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"

  UrlShortenerTests:
    type: bundle.unit-test
    platform: iOS
    sources: [UrlShortenerTests]
    dependencies:
    - target: UrlShortener
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
        BUNDLE_LOADER: $(TEST_HOST)
        GENERATE_INFOPLIST_FILE: 'YES'
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/UrlShortener.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/UrlShortener

  UrlShortenerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [UrlShortenerUITests]
    dependencies:
    - target: UrlShortener
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
        GENERATE_INFOPLIST_FILE: 'YES'
        TEST_TARGET_NAME: UrlShortener
  
schemes:
  UrlShortener:
    build:
      targets:
        UrlShortener: all
        UrlShortenerTests: [test]
        UrlShortenerUITests: [test]
        Cache/CacheProvider: [test]
        Network/NetworkProvider: [test]
    test:
      gatherCoverageData: YES
      coverageTargets:
        - UrlShortener
        - Cache/CacheProvider
        - Network/NetworkProvider
      targets:
        - name: UrlShortenerTests
          paralelizable: true
        - name: UrlShortenerUITests
          paralelizable: true
        - name: Cache/CacheProviderTests
          paralelizable: true
        - name: Network/NetworkProviderTests
          paralelizable: true
